In [137]:

#Final Project
import os
import pandas as pd
import numpy as np
import datetime as dt
import matplotlib.pyplot as plt
import seaborn as sns
import yfinance as yf

# Web scaping an etf ticker's data from an excel file within a download link. 
stocks = pd.read_excel('https://www.ssga.com/us/en/intermediary/etfs/library-content/products/fund-data/etfs/us/holdings-daily-us-en-spy.xlsx',
                        header=4).Ticker.dropna().to_list()

stocks = [ticker.upper() for ticker in stocks] 

# Gathers asset's data from past 5 years (1825 days) to today 
start_date = dt.datetime.today() - pd.Timedelta(1825, "d")
end_date = dt.datetime.today()

#Downloads stock data
data =yf.download (start=start_date,end=end_date, tickers= stocks)['Adj Close']
data= pd.DataFrame(data).dropna(how='all', axis=1) 

data2 =yf.download (start=start_date,end=end_date, tickers= stocks )
data2= pd.DataFrame(data2).dropna(how='all', axis=1)

data3 =yf.download (start=start_date,end=end_date, tickers= stocks )['Volume'] #for volume trendline
data3= pd.DataFrame(data).dropna(how='all', axis=1)

[*********************100%%**********************]  504 of 504 completed

3 Failed downloads:
['BF.B']: Exception('%ticker%: No price data found, symbol may be delisted (1d 2019-05-14 14:15:26.436830 -> 2024-05-12 14:15:26.437017)')
['BRK.B', '-']: Exception('%ticker%: No timezone found, symbol may be delisted')
[*********************100%%**********************]  504 of 504 completed

3 Failed downloads:
['BF.B']: Exception('%ticker%: No price data found, symbol may be delisted (1d 2019-05-14 14:15:26.436830 -> 2024-05-12 14:15:26.437017)')
['BRK.B', '-']: Exception('%ticker%: No timezone found, symbol may be delisted')
[*********************100%%**********************]  504 of 504 completed

3 Failed downloads:
['BF.B']: Exception('%ticker%: No price data found, symbol may be delisted (1d 2019-05-14 14:15:26.436830 -> 2024-05-12 14:15:26.437017)')
['BRK.B', '-']: Exception('%ticker%: No timezone found, symbol may be delisted')

52 weeks trendline slopes

In [138]:
slopes=pd.DataFrame(index=data.columns)

#for trendline: use np.polyfit

def trendline (data):
    for ind in range (1,21):
        slopes[ind]=np.polyfit(range(252),data[-252 - ind : - ind], 1)[0] #collect this into empty DF, slopes . using range 252 days but step back once each time to get 20 day avg.

    return slopes.mean(axis=1) #returns avg slope of last 20 days by column(thetickers)

trendline(data=data.pct_change())

Ticker
A       1.640381e-05
AAL    -6.799076e-06
AAPL   -1.177110e-05
ABBV    8.332255e-06
ABNB    2.207549e-07
            ...
XYL     1.509589e-05
YUM     9.107111e-06
ZBH     7.342834e-06
ZBRA    1.945766e-05
ZTS    -1.243484e-05
Length: 501, dtype: float64

In [139]:
slopes

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
Ticker,,,,,,,,,,,,,,,,,,,,
A,1.488087e-05,1.707314e-05,1.672773e-05,1.675913e-05,1.665370e-05,0.000015,1.711946e-05,1.556522e-05,1.579260e-05,1.448677e-05,0.000012,0.000018,1.914282e-05,1.336357e-05,1.484052e-05,0.000015,1.694891e-05,0.000018,0.000022,0.000020
AAL,3.925252e-06,2.860440e-06,-1.542489e-06,-1.389259e-06,-4.846219e-06,-0.000005,-5.949931e-06,-8.133742e-06,-1.045525e-05,-1.206096e-05,-0.000010,-0.000007,-4.740496e-06,-3.251516e-06,-3.819042e-06,-0.000007,-8.921412e-06,-0.000017,-0.000017,-0.000015
AAPL,-3.119255e-06,-3.061799e-06,-3.146634e-06,-7.870733e-06,-5.989263e-06,-0.000011,-1.244354e-05,-1.180680e-05,-1.076599e-05,-1.575480e-05,-0.000015,-0.000015,-1.628928e-05,-1.595223e-05,-1.587419e-05,-0.000015,-1.551619e-05,-0.000015,-0.000013,-0.000014
ABBV,3.941915e-07,8.987207e-07,2.569285e-06,2.329415e-06,4.222369e-06,0.000004,5.888692e-06,4.863458e-06,2.851538e-06,9.317289e-06,0.000015,0.000015,1.532244e-05,1.404754e-05,1.293742e-05,0.000011,1.174261e-05,0.000011,0.000011,0.000011
ABNB,-1.879039e-06,3.736129e-06,5.772778e-07,3.090204e-07,2.128607e-07,0.000001,5.873139e-07,8.915497e-07,-3.050570e-07,-1.542528e-07,-0.000002,0.000002,3.237075e-07,2.995848e-07,9.129881e-07,0.000003,2.413079e-07,-0.000002,-0.000003,-0.000001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
XYL,2.240200e-05,2.215937e-05,2.299442e-05,2.029468e-05,1.716568e-05,0.000017,1.341984e-05,1.281634e-05,1.434608e-05,1.175128e-05,0.000012,0.000014,1.414821e-05,1.278082e-05,1.186578e-05,0.000012,1.180706e-05,0.000013,0.000013,0.000013
YUM,8.831181e-06,7.412499e-06,7.348681e-06,6.729939e-06,6.118041e-06,0.000010,1.001203e-05,1.285598e-05,1.362917e-05,1.148586e-05,0.000011,0.000012,1.065299e-05,9.394457e-06,8.768005e-06,0.000009,8.320149e-06,0.000007,0.000007,0.000005
ZBH,8.002687e-06,8.422995e-06,9.117211e-06,7.472464e-06,1.026855e-05,0.000010,7.765650e-06,7.973575e-06,8.938687e-06,7.478036e-06,0.000008,0.000008,8.115395e-06,7.748811e-06,6.435012e-06,0.000004,4.463754e-06,0.000004,0.000006,0.000005
ZBRA,2.093423e-05,2.474581e-05,2.289772e-05,1.932212e-05,1.525034e-05,0.000015,2.483853e-05,2.681183e-05,2.105006e-05,1.902245e-05,0.000019,0.000015,1.474225e-05,1.390514e-05,1.338095e-05,0.000018,1.857645e-05,0.000021,0.000023,0.000023
ZTS,-1.058938e-06,-2.692036e-06,-7.485935e-08,-5.643476e-06,-5.425766e-06,-0.000006,-9.639351e-06,-1.128866e-05,-1.205227e-05,-1.340505e-05,-0.000017,-0.000016,-1.702061e-05,-2.107783e-05,-2.025319e-05,-0.000017,-1.726104e-05,-0.000017,-0.000019,-0.000020

Percent above 260 day low

In [140]:
#Low from 260 days
price_low = data2['Low'][-260:][-20:]
price_low
#current and lowest price
current_price= price_low.iloc[-1:]
lowest_price= price_low.min()

#percentage above 260 days
precentabove_lows =((current_price - lowest_price) / lowest_price) * 100
precentabove_lows

Ticker,A,AAL,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,...,WTW,WY,WYNN,XEL,XOM,XYL,YUM,ZBH,ZBRA,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2024-05-10,13.074645,12.578612,11.000733,1.712662,0.0,0.163068,11.328127,2.670242,4.331393,12.417154,...,3.872839,2.897099,4.816641,5.673765,3.022873,14.150488,1.836923,3.472161,17.788196,16.222369

4/52 week price oscillator

In [141]:
#52 weeks
fiftytwo_weekclose= data2['Close'][-252:]
fiftytwo_weekclose=fiftytwo_weekclose.ewm(span=252, min_periods=20).mean()[-20:].dropna()

#4 weeks
fourweek_close= data2['Close'][-20:]
fourweek_close=fourweek_close.ewm(span=20, min_periods=20).mean().dropna()

#price oscillator
price_oscillator =((fourweek_close-fiftytwo_weekclose)/fiftytwo_weekclose)*100
price_oscillator.dropna()

Ticker,A,AAL,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,...,WTW,WY,WYNN,XEL,XOM,XYL,YUM,ZBH,ZBRA,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2024-05-10,7.063683,-0.182228,-1.960896,1.475294,7.830296,-1.989233,12.982078,-7.90946,-10.713809,5.674676,...,3.243307,-4.722593,-0.970206,-5.248965,7.973016,17.065534,3.859115,-1.364318,13.971964,-8.377985

39 week returns

In [142]:
weekreturns= data
weekreturns=weekreturns.pct_change(189)[-20:].mean()
weekreturns

Ticker
A       0.108655
AAL    -0.165914
AAPL   -0.085788
ABBV    0.127699
ABNB    0.088232
          ...
XYL     0.210645
YUM     0.019207
ZBH    -0.103710
ZBRA    0.057299
ZTS    -0.133328
Length: 501, dtype: float64

51 week volume price trend

In [143]:
vol = data2['Volume'][-240:]
price_close= data2['Close'][-240:]

# Volume Price Trend 

VPT = [0]  # Initial VPT 

for i in range(1, 21):
    volume = vol.iloc[i]
    close_price = price_close.iloc[i]
    previous_close_price = price_close.iloc[i - 1]
    previousvpt = VPT[-1]  # Gets previous VPT value
    vpt = (volume * (close_price - previous_close_price / previous_close_price))+ previousvpt 
    
vpt

Ticker
A       2.534448e+08
AAL     4.380172e+08
AAPL    9.641563e+09
ABBV    9.089839e+08
ABNB    7.762925e+08
            ...
XYL     1.286438e+08
YUM     1.575843e+08
ZBH     1.458314e+08
ZBRA    8.491649e+07
ZTS     2.835511e+08
Length: 501, dtype: float64

Z-scores

In [144]:
import scipy
import scipy.stats as stats

data = data.pct_change()

zscore = scipy.stats.zscore(data, axis=0, ddof=0, nan_policy='omit')
zscore

Ticker,A,AAL,AAPL,ABBV,ABNB,ABT,ACGL,ACN,ADBE,ADI,...,WTW,WY,WYNN,XEL,XOM,XYL,YUM,ZBH,ZBRA,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2019-05-14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-05-15,-5.961366,-0.145891,0.534304,0.221032,NaN,0.357952,0.158875,0.534936,0.739787,0.451061,...,0.026399,-0.072696,0.444483,-0.107822,0.308420,0.599566,0.035031,-0.098236,-0.343408,0.286901
2019-05-16,1.280693,0.125552,-0.284718,0.523485,NaN,0.045746,0.604859,0.838289,0.996172,-1.387098,...,0.801196,0.156976,0.467731,0.549452,-0.039455,-0.164362,0.283986,-0.214080,0.966814,0.553892
2019-05-17,-0.186628,-0.464680,-0.348823,-0.083452,NaN,-0.525632,-1.057191,0.014118,-0.582648,-1.724875,...,-0.692947,-1.183465,-1.362241,0.511937,-0.306147,-0.734846,0.234087,-0.726816,-2.214927,-0.542890
2019-05-20,-0.179263,-0.635387,-1.628345,0.233377,NaN,-0.185763,0.061045,0.029608,-0.695645,-1.545064,...,0.094984,-1.519920,-0.310209,0.184510,-0.039511,-0.526870,-0.392828,-0.230853,-1.273626,0.102065
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-05-06,0.408186,1.484869,-0.520091,-0.459159,0.426825,-0.174979,1.323162,0.392584,0.612862,0.807536,...,0.220835,-0.036695,0.337809,0.117763,0.265785,0.704668,0.809109,-0.471983,0.733982,-0.399262
2024-05-07,0.213254,-0.705664,0.125168,-0.121416,-0.434513,0.279168,0.472117,0.796078,-0.144233,0.019472,...,0.381473,-0.326498,-0.203022,0.751860,-0.263313,0.267783,-0.146614,0.353895,0.221853,0.792722
2024-05-08,0.543277,0.304646,0.028504,-0.864998,-0.386067,-0.729884,0.296986,0.201324,-0.389193,0.252734,...,-0.455838,-0.182778,-0.456379,-0.111925,-0.041382,0.390178,0.445156,-0.255318,0.220215,-1.179654
2024-05-09,0.842094,0.104586,0.436050,-0.071410,-2.141167,-0.182137,0.284837,-0.989741,-0.503074,-0.052295,...,0.577590,0.509381,0.426650,0.344471,0.878966,0.473586,0.414837,0.235320,-0.440015,1.033611
2024-05-10,1.672725,-0.144833,-0.476517,0.085560,-0.170015,0.014888,0.148869,-0.086097,-0.062738,0.498568,...,0.271449,-0.233951,-0.252397,0.240331,-0.220962,0.102662,-0.171580,-0.067064,-0.113408,0.264187

10 Long and Short Baskets

In [145]:
mean_zscores = zscore.mean().sort_values(ascending=False)

long_assets = mean_zscores.head(10).index.tolist()  # Adjusts to basket size 
short_assets = mean_zscores.tail(10).index.tolist()
print("Long Basket:",long_assets)
print("Short Basket:",short_assets)

Long Basket: ['TRMB', 'WST', 'FE', 'ETN', 'OXY', 'ISRG', 'CAT', 'SOLV', 'RJF', 'PODD']
Short Basket: ['DIS', 'CVX', 'UBER', 'CAH', 'BA', 'KVUE', 'MRNA', 'EA', 'PARA', 'BBWI']

Backtest